package launcher

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"hash"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// ComputeHash returns a deterministic SHA256 hex string for the given extensions.
// The hash covers the Go version, OS/arch, the headless flag, the agent loop, the root module's go.mod and go.sum,
// the sorted contents of all extension .go files, and the contents of any additional core
// package directories.
func ComputeHash(exts []ExtensionInfo, moduleRoot, moduleVersion string, headless bool, agentLoop string, coreDirs ...string) (string, error) {
	h := sha256.New()

	h.Write([]byte("go" + runtime.Version() + "\n"))
	h.Write([]byte("os:" + runtime.GOOS + "\n"))
	h.Write([]byte("arch:" + runtime.GOARCH + "\n"))
	h.Write([]byte("headless:" + strconv.FormatBool(headless) + "\n"))
	h.Write([]byte("agentLoop:" + agentLoop + "\n"))

	HashModuleGraph(h, moduleRoot, moduleVersion)

	sorted := make([]ExtensionInfo, len(exts))
	copy(sorted, exts)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	for _, ext := range sorted {
		h.Write([]byte("ext:" + ext.Name + "\n"))

		for _, f := range ext.GoFiles {
			rel, relErr := filepath.Rel(ext.Dir, f)
			if relErr != nil {
				rel = f
			}

			h.Write([]byte(rel + "\n"))

			data, err := os.ReadFile(f)
			if err != nil {
				return "", fmt.Errorf("hash: read %s: %w", f, err)
			}

			h.Write(data)
		}

		// Hash embedded resource files (e.g., go:embed agents/*.md).
		// These affect the compiled binary but are not .go files.
		if err := hashEmbeddedFiles(h, ext); err != nil {
			return "", fmt.Errorf("hash: embedded files for %s: %w", ext.Name, err)
		}

		goModPath := filepath.Join(ext.Dir, "go.mod")
		if data, err := os.ReadFile(goModPath); err == nil {
			// Skip shim go.mods generated by ensureExtGoMod — they are
			// build artifacts, not extension inputs.
			if !strings.HasPrefix(string(data), shimSentinel) {
				h.Write([]byte("go.mod\n"))
				h.Write(data)

				goSumPath := filepath.Join(ext.Dir, "go.sum")
				if sumData, sumErr := os.ReadFile(goSumPath); sumErr == nil {
					h.Write([]byte("go.sum\n"))
					h.Write(sumData)
				}
			}
		}
	}

	for _, dir := range coreDirs {
		if err := hashDir(h, dir); err != nil {
			return "", fmt.Errorf("hash: core dir %s: %w", dir, err)
		}
	}

	// Hash transitive local dependencies discovered from extension go.mod files.
	// These are shared libraries (e.g. openaicompat) that extensions depend on
	// via replace directives. Without this, changes to shared libs don't
	// invalidate the cache.
	absModuleRoot, _ := filepath.Abs(moduleRoot)

	var transitiveDeps []struct{ modPath, dir string }

	transitiveSeen := make(map[string]bool)

	for _, ext := range sorted {
		for depModPath, depDir := range readLocalReplaces(ext.Dir) {
			if transitiveSeen[depDir] {
				continue
			}

			// Skip the root module — already hashed via HashModuleGraph and
			// coreDirs. Only applicable in dev mode where moduleRoot is non-empty.
			if moduleRoot != "" && depDir == absModuleRoot {
				continue
			}

			transitiveSeen[depDir] = true
			transitiveDeps = append(transitiveDeps, struct{ modPath, dir string }{depModPath, depDir})
		}
	}

	sort.Slice(transitiveDeps, func(i, j int) bool {
		return transitiveDeps[i].modPath < transitiveDeps[j].modPath
	})

	for _, dep := range transitiveDeps {
		h.Write([]byte("transitive:" + dep.modPath + "\n"))

		if err := hashDir(h, dep.dir); err != nil {
			return "", fmt.Errorf("hash: transitive dep %s: %w", dep.dir, err)
		}
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}

// hashEmbeddedFiles hashes resources referenced by //go:embed directives in
// extension source files. The Go compiler treats these resources as build
// inputs, so launcher cache keys must include them too.
func hashEmbeddedFiles(h hash.Hash, ext ExtensionInfo) error {
	files, err := embeddedResourceFiles(ext)
	if err != nil {
		return err
	}

	absRoot, err := filepath.Abs(ext.Dir)
	if err != nil {
		return fmt.Errorf("abs extension dir: %w", err)
	}

	for _, rel := range files {
		h.Write([]byte("embed:" + rel + "\n"))

		data, readErr := os.ReadFile(filepath.Join(absRoot, filepath.FromSlash(rel)))
		if readErr != nil {
			return fmt.Errorf("read %s: %w", rel, readErr)
		}

		h.Write(data)
	}

	return nil
}

func embeddedResourceFiles(ext ExtensionInfo) ([]string, error) {
	absRoot, err := filepath.Abs(ext.Dir)
	if err != nil {
		return nil, fmt.Errorf("abs extension dir: %w", err)
	}

	goFiles := append([]string(nil), ext.GoFiles...)
	sort.Strings(goFiles)

	goFileSet := make(map[string]struct{}, len(goFiles))
	for _, goFile := range goFiles {
		absGoFile, absErr := filepath.Abs(goFile)
		if absErr != nil {
			return nil, fmt.Errorf("abs go file %s: %w", goFile, absErr)
		}

		rel, relErr := filepath.Rel(absRoot, absGoFile)
		if relErr == nil && !isRelOutside(rel) {
			goFileSet[filepath.ToSlash(rel)] = struct{}{}
		}
	}

	seen := make(map[string]struct{})
	for _, goFile := range goFiles {
		if strings.HasSuffix(goFile, "_test.go") {
			continue
		}

		absGoFile, absErr := filepath.Abs(goFile)
		if absErr != nil {
			return nil, fmt.Errorf("abs go file %s: %w", goFile, absErr)
		}

		patterns, parseErr := embedPatternsFromGoFile(absGoFile)
		if parseErr != nil {
			return nil, parseErr
		}

		for _, pattern := range patterns {
			matches, matchErr := matchEmbedPattern(absRoot, filepath.Dir(absGoFile), pattern)
			if matchErr != nil {
				return nil, fmt.Errorf("%s: %w", goFile, matchErr)
			}

			for _, rel := range matches {
				if _, alreadyGoFile := goFileSet[rel]; alreadyGoFile {
					continue
				}

				seen[rel] = struct{}{}
			}
		}
	}

	files := make([]string, 0, len(seen))
	for rel := range seen {
		files = append(files, rel)
	}

	sort.Strings(files)

	return files, nil
}

func embedPatternsFromGoFile(goFile string) ([]string, error) {
	fileSet := token.NewFileSet()
	parsed, err := parser.ParseFile(fileSet, goFile, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", goFile, err)
	}

	var (
		patterns []string
		parseErr error
	)

	appendFromDoc := func(doc *ast.CommentGroup) {
		if doc == nil || parseErr != nil {
			return
		}

		for _, comment := range doc.List {
			found, err := parseEmbedComment(comment.Text)
			if err != nil {
				parseErr = fmt.Errorf("%s: %w", goFile, err)

				return
			}

			patterns = append(patterns, found...)
		}
	}

	ast.Inspect(parsed, func(n ast.Node) bool {
		if parseErr != nil {
			return false
		}

		decl, ok := n.(*ast.GenDecl)
		if !ok || decl.Tok != token.VAR {
			return true
		}

		appendFromDoc(decl.Doc)
		for _, spec := range decl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			appendFromDoc(valueSpec.Doc)
		}

		return false
	})
	if parseErr != nil {
		return nil, parseErr
	}

	return patterns, nil
}

func parseEmbedComment(text string) ([]string, error) {
	const prefix = "//go:embed"

	if !strings.HasPrefix(text, prefix) {
		return nil, nil
	}

	rest := strings.TrimPrefix(text, prefix)
	if rest != "" {
		r, _ := utf8.DecodeRuneInString(rest)
		if !unicode.IsSpace(r) {
			return nil, nil
		}
	}

	patterns, err := splitEmbedPatterns(strings.TrimSpace(rest))
	if err != nil {
		return nil, err
	}

	if len(patterns) == 0 {
		return nil, errors.New("go:embed directive has no patterns")
	}

	return patterns, nil
}

func splitEmbedPatterns(s string) ([]string, error) {
	var patterns []string

	for {
		s = strings.TrimLeftFunc(s, unicode.IsSpace)
		if s == "" {
			break
		}

		switch s[0] {
		case '`':
			end := strings.IndexByte(s[1:], '`')
			if end == -1 {
				return nil, errors.New("unterminated raw string in go:embed directive")
			}

			lit := s[:end+2]
			pattern, err := strconv.Unquote(lit)
			if err != nil {
				return nil, fmt.Errorf("unquote go:embed pattern %s: %w", lit, err)
			}

			patterns = append(patterns, pattern)
			s = s[len(lit):]
		case '"':
			end, err := quotedStringEnd(s)
			if err != nil {
				return nil, err
			}

			lit := s[:end]
			pattern, unquoteErr := strconv.Unquote(lit)
			if unquoteErr != nil {
				return nil, fmt.Errorf("unquote go:embed pattern %s: %w", lit, unquoteErr)
			}

			patterns = append(patterns, pattern)
			s = s[len(lit):]
		default:
			end := strings.IndexFunc(s, unicode.IsSpace)
			if end == -1 {
				patterns = append(patterns, s)
				s = ""
			} else {
				patterns = append(patterns, s[:end])
				s = s[end:]
			}
		}
	}

	return patterns, nil
}

func quotedStringEnd(s string) (int, error) {
	escaped := false
	for i := 1; i < len(s); i++ {
		switch {
		case escaped:
			escaped = false
		case s[i] == '\\':
			escaped = true
		case s[i] == '"':
			return i + 1, nil
		}
	}

	return 0, errors.New("unterminated string in go:embed directive")
}

func matchEmbedPattern(moduleRoot, pkgDir, rawPattern string) ([]string, error) {
	original := rawPattern
	all := false
	if after, ok := strings.CutPrefix(rawPattern, "all:"); ok {
		all = true
		rawPattern = after
	}

	if err := validateEmbedPattern(rawPattern); err != nil {
		return nil, fmt.Errorf("embed pattern %q: %w", original, err)
	}

	matches, err := filepath.Glob(filepath.Join(pkgDir, filepath.FromSlash(rawPattern)))
	if err != nil {
		return nil, fmt.Errorf("embed pattern %q: %w", original, err)
	}

	sort.Strings(matches)

	var files []string
	for _, match := range matches {
		absMatch, absErr := filepath.Abs(match)
		if absErr != nil {
			return nil, fmt.Errorf("abs match %s: %w", match, absErr)
		}

		if !isWithinDir(moduleRoot, absMatch) || !withinModuleBoundary(moduleRoot, absMatch) {
			continue
		}

		info, statErr := os.Lstat(absMatch)
		if statErr != nil {
			return nil, fmt.Errorf("stat %s: %w", match, statErr)
		}

		switch {
		case info.IsDir():
			dirFiles, dirErr := embeddedDirFiles(moduleRoot, absMatch, all)
			if dirErr != nil {
				return nil, fmt.Errorf("directory %s: %w", match, dirErr)
			}

			files = append(files, dirFiles...)
		case info.Mode().IsRegular():
			rel, relErr := filepath.Rel(moduleRoot, absMatch)
			if relErr != nil {
				return nil, fmt.Errorf("rel %s: %w", match, relErr)
			}

			files = append(files, filepath.ToSlash(rel))
		}
	}

	if len(files) == 0 {
		return nil, fmt.Errorf("embed pattern %q matched no files", original)
	}

	sort.Strings(files)

	return files, nil
}

func validateEmbedPattern(pattern string) error {
	if pattern == "" {
		return errors.New("empty pattern")
	}

	if strings.HasPrefix(pattern, "/") || strings.HasSuffix(pattern, "/") {
		return errors.New("pattern must not begin or end with slash")
	}

	for _, elem := range strings.Split(pattern, "/") {
		if elem == "" || elem == "." || elem == ".." {
			return fmt.Errorf("invalid path element %q", elem)
		}
	}

	if path.Clean(pattern) != pattern {
		return errors.New("pattern must be clean")
	}

	return nil
}

func embeddedDirFiles(moduleRoot, dir string, all bool) ([]string, error) {
	var files []string

	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, entryErr error) error {
		if entryErr != nil {
			return entryErr
		}

		if path == dir {
			return nil
		}

		name := d.Name()
		if d.IsDir() {
			if _, statErr := os.Stat(filepath.Join(path, "go.mod")); statErr == nil {
				return fs.SkipDir
			}

			if !all && (strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")) {
				return fs.SkipDir
			}

			return nil
		}

		if !d.Type().IsRegular() {
			return nil
		}

		if !all && (strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")) {
			return nil
		}

		if !withinModuleBoundary(moduleRoot, path) {
			return nil
		}

		rel, relErr := filepath.Rel(moduleRoot, path)
		if relErr != nil {
			return fmt.Errorf("rel %s: %w", path, relErr)
		}

		files = append(files, filepath.ToSlash(rel))

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk: %w", err)
	}

	sort.Strings(files)

	return files, nil
}

func withinModuleBoundary(moduleRoot, candidate string) bool {
	absRoot, rootErr := filepath.Abs(moduleRoot)
	if rootErr != nil {
		return false
	}

	absCandidate, candidateErr := filepath.Abs(candidate)
	if candidateErr != nil {
		return false
	}

	if !isWithinDir(absRoot, absCandidate) {
		return false
	}

	info, err := os.Lstat(absCandidate)
	if err == nil && !info.IsDir() {
		absCandidate = filepath.Dir(absCandidate)
	}

	for {
		if samePath(absCandidate, absRoot) {
			return true
		}

		if _, statErr := os.Stat(filepath.Join(absCandidate, "go.mod")); statErr == nil {
			return false
		}

		parent := filepath.Dir(absCandidate)
		if parent == absCandidate {
			return false
		}

		absCandidate = parent
	}
}

func isWithinDir(root, candidate string) bool {
	rel, err := filepath.Rel(root, candidate)
	if err != nil {
		return false
	}

	return !isRelOutside(rel)
}

func isRelOutside(rel string) bool {
	return rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(rel)
}

func samePath(a, b string) bool {
	rel, err := filepath.Rel(a, b)
	return err == nil && rel == "."
}

// HashModuleGraph writes the root go.mod and go.sum contents into the hash,
// so changes to the module graph (dependency versions, toolchain directives)
// invalidate the cache even when no .go files changed.
// In release mode (moduleRoot == ""), the version string is hashed instead.
func HashModuleGraph(h hash.Hash, moduleRoot, moduleVersion string) {
	if moduleRoot == "" {
		h.Write([]byte("version:" + moduleVersion + "\n"))
		return
	}

	for _, name := range []string{"go.mod", "go.sum"} {
		data, err := os.ReadFile(filepath.Join(moduleRoot, name))
		if err != nil {
			continue
		}

		h.Write([]byte(name + "\n"))
		h.Write(data)
	}
}

func hashDir(h hash.Hash, dir string) error {
	var files []string

	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			return nil
		}

		name := d.Name()
		if (strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")) || name == "go.mod" || name == "go.sum" {
			files = append(files, path)
		}

		return nil
	})
	if err != nil {
		return fmt.Errorf("walk dir: %w", err)
	}

	sort.Strings(files)

	for _, f := range files {
		rel, relErr := filepath.Rel(dir, f)
		if relErr != nil {
			rel = f
		}

		h.Write([]byte(rel + "\n"))

		data, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("read %s: %w", f, err)
		}

		h.Write(data)
	}

	return nil
}

// goVersion returns the Go version string for go.mod (e.g. "go 1.22.0").
func goVersion() string {
	// runtime.Version() returns e.g. "go1.22.0", "go1.22.0 X:loopvar", "go1.26.2-X:jsonv2"
	v := strings.TrimPrefix(runtime.Version(), "go")
	// Strip anything after a space or dash that isn't a digit/dot
	if idx := strings.IndexFunc(v, func(r rune) bool {
		return !strings.ContainsRune("0123456789.", r)
	}); idx != -1 {
		v = v[:idx]
	}

	return "go " + v
}

// extModulePath returns the module path for an extension, reading it from
// the extension's go.mod. Falls back to "github.com/weave-agent/weave/ext/{name}" if unavailable.
func extModulePath(ext ExtensionInfo) string {
	if ext.ModulePath != "" {
		return ext.ModulePath
	}

	return "github.com/weave-agent/weave/ext/" + ext.Name
}

// readModulePath reads the module path from a go.mod file in dir.
func readModulePath(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return ""
	}

	for line := range strings.SplitSeq(string(data), "\n") {
		if after, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.TrimSpace(after)
		}
	}

	return ""
}

// GenerateGoMod creates a go.mod file for the built binary.
// moduleRoot is the path to the weave module root (containing go.mod).
func GenerateGoMod(dir, moduleRoot, moduleVersion string, exts []ExtensionInfo) error {
	var b strings.Builder
	b.WriteString("module github.com/weave-agent/weave/built\n\n")
	b.WriteString(goVersion() + "\n\n")
	b.WriteString("require (\n")

	if moduleRoot != "" {
		b.WriteString("\tgithub.com/weave-agent/weave v0.0.0\n")
	} else {
		b.WriteString("\tgithub.com/weave-agent/weave " + moduleVersion + "\n")
	}

	for _, ext := range exts {
		b.WriteString("\t" + extModulePath(ext) + " v0.0.0\n")
	}

	// Propagate transitive local dependencies from extension go.mod files.
	directModulePaths := make(map[string]bool)

	directModulePaths["github.com/weave-agent/weave"] = true
	for _, ext := range exts {
		directModulePaths[extModulePath(ext)] = true
	}

	var (
		extraRequires []string
		extraReplaces []string
	)

	for _, ext := range exts {
		localReplaces := readLocalReplaces(ext.Dir)
		for modPath, localPath := range localReplaces {
			if directModulePaths[modPath] {
				continue
			}

			directModulePaths[modPath] = true
			extraRequires = append(extraRequires, modPath+" v0.0.0")
			extraReplaces = append(extraReplaces, "replace "+modPath+" => "+localPath)
		}
	}

	sort.Strings(extraRequires)
	sort.Strings(extraReplaces)

	for _, req := range extraRequires {
		b.WriteString("\t" + req + "\n")
	}

	b.WriteString(")\n\n")

	if moduleRoot != "" {
		b.WriteString("replace github.com/weave-agent/weave => " + moduleRoot + "\n")
	}

	for _, ext := range exts {
		b.WriteString("replace " + extModulePath(ext) + " => " + ext.Dir + "\n")
	}

	for _, rep := range extraReplaces {
		b.WriteString(rep + "\n")
	}

	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("generate go.mod: %w", err)
	}

	return nil
}

// readLocalReplaces parses a go.mod file and returns replace directives that
// point to local paths (relative or absolute). The returned map keys are
// module paths and values are resolved absolute paths.
func readLocalReplaces(dir string) map[string]string {
	data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return nil
	}

	result := make(map[string]string)
	inReplaceBlock := false

	for line := range strings.SplitSeq(string(data), "\n") {
		trimmed := stripGoModComment(strings.TrimSpace(line))

		if trimmed == "" {
			continue
		}

		if strings.HasPrefix(trimmed, "replace ") {
			if strings.Contains(trimmed, "=>") {
				parseSingleReplace(trimmed[len("replace "):], dir, result)
			} else {
				inReplaceBlock = true
			}

			continue
		}

		if inReplaceBlock {
			if trimmed == ")" {
				inReplaceBlock = false

				continue
			}

			if strings.Contains(trimmed, "=>") {
				parseSingleReplace(trimmed, dir, result)
			}
		}
	}

	return result
}

// stripGoModComment removes any "//"-prefixed inline comment from a go.mod
// line. go.mod has no escape syntax so anything after "//" is comment text.
func stripGoModComment(line string) string {
	if before, _, found := strings.Cut(line, "//"); found {
		return strings.TrimSpace(before)
	}

	return line
}

func parseSingleReplace(s, dir string, result map[string]string) {
	before, after, ok := strings.Cut(s, "=>")
	if !ok {
		return
	}

	// The left side may include a version (e.g. "example.com/lib v1.2.3").
	// Strip it so modPath is just the module path.
	modPath, _, _ := strings.Cut(strings.TrimSpace(before), " ")
	localPath := strings.TrimSpace(after)

	if localPath == "" {
		return
	}

	// Only capture local paths (relative or absolute), not version queries.
	if !strings.HasPrefix(localPath, ".") && !strings.HasPrefix(localPath, "/") {
		return
	}

	absPath := localPath
	if !strings.HasPrefix(localPath, "/") {
		absPath = filepath.Join(dir, localPath)
	}

	// Skip resolved paths without a go.mod — not a valid Go module.
	if _, statErr := os.Stat(filepath.Join(absPath, "go.mod")); statErr != nil {
		return
	}

	result[modPath] = absPath
}

// GenerateMainGo creates a main.go that creates a bus, wires all extensions, and blocks on signal.
// The generated binary accepts:
//   - --weave-config=<path> to pass config to extensions
//   - --weave-prompt-file=<path> to read the initial prompt from a file
//   - --weave-agent-loop=<name> for core wiring
//   - --weave-project-dir=<path> to override project dir for settings resolution
func GenerateMainGo(dir string, exts []ExtensionInfo, agentLoop string) error {
	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/signal\"\n")
	b.WriteString("\t\"path/filepath\"\n")
	b.WriteString("\t\"strconv\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"sync\"\n")
	b.WriteString("\t\"syscall\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/weave-agent/weave/bus\"\n")
	b.WriteString("\t\"github.com/weave-agent/weave/internal/log\"\n")
	b.WriteString("\t\"github.com/weave-agent/weave/settings\"\n")
	b.WriteString("\t\"github.com/weave-agent/weave/sdk\"\n")
	b.WriteString("\t\"github.com/weave-agent/weave/sdk/model\"\n")
	b.WriteString("\t\"github.com/weave-agent/weave/internal/wire\"\n")

	for _, ext := range exts {
		b.WriteString("\n")
		b.WriteString("\t_ \"" + extModulePath(ext) + "\"\n")
	}

	b.WriteString(")\n\n")
	b.WriteString("type syncWriter struct {\n")
	b.WriteString("\tmu sync.Mutex\n")
	b.WriteString("\tw  io.Writer\n")
	b.WriteString("}\n\n")
	b.WriteString("func (sw *syncWriter) Write(p []byte) (int, error) {\n")
	b.WriteString("\tsw.mu.Lock()\n")
	b.WriteString("\tdefer sw.mu.Unlock()\n")
	b.WriteString("\treturn sw.w.Write(p)\n")
	b.WriteString("}\n\n")
	b.WriteString("func main() {\n")
	b.WriteString("\tvar cfgPath string\n")
	b.WriteString("\tvar promptFilePath string\n")
	b.WriteString("\tvar agentLoopName string\n")
	b.WriteString("\tvar headlessFlag string\n")
	b.WriteString("\tvar projectDir string\n")
	b.WriteString("\tvar outputMode string\n")
	b.WriteString("\tvar toolsList string\n")
	b.WriteString("\tvar toolsSet bool\n")
	b.WriteString("\tvar subagentID string\n")
	b.WriteString("\tvar sandboxMode string\n")
	b.WriteString("\tvar modelOverride string\n")
	b.WriteString("\tvar messaging string\n")
	b.WriteString("\tvar debugFlag string\n")
	b.WriteString("\tvar continueFlag string\n")
	b.WriteString("\tvar resumeID string\n")
	b.WriteString("\tfiltered := make([]string, 0, len(os.Args)-1)\n")
	b.WriteString("\tfor _, a := range os.Args[1:] {\n")
	b.WriteString("\t\tif p, ok := strings.CutPrefix(a, \"--weave-config=\"); ok {\n")
	b.WriteString("\t\t\tcfgPath = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-prompt-file=\"); ok {\n")
	b.WriteString("\t\t\tpromptFilePath = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-agent-loop=\"); ok {\n")
	b.WriteString("\t\t\tagentLoopName = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-headless=\"); ok {\n")
	b.WriteString("\t\t\theadlessFlag = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-project-dir=\"); ok {\n")
	b.WriteString("\t\t\tprojectDir = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-output=\"); ok {\n")
	b.WriteString("\t\t\toutputMode = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-tools=\"); ok {\n")
	b.WriteString("\t\t\ttoolsList = p\n")
	b.WriteString("\t\t\ttoolsSet = true\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-subagent-id=\"); ok {\n")
	b.WriteString("\t\t\tsubagentID = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-sandbox-mode=\"); ok {\n")
	b.WriteString("\t\t\tsandboxMode = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-model=\"); ok {\n")
	b.WriteString("\t\t\tmodelOverride = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-messaging=\"); ok {\n")
	b.WriteString("\t\t\tmessaging = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-debug=\"); ok {\n")
	b.WriteString("\t\t\tdebugFlag = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-continue=\"); ok {\n")
	b.WriteString("\t\t\tcontinueFlag = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-resume=\"); ok {\n")
	b.WriteString("\t\t\tresumeID = p\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tfiltered = append(filtered, a)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tos.Args = append([]string{os.Args[0]}, filtered...)\n\n")

	b.WriteString("\tfor _, a := range filtered {\n")
	b.WriteString("\t\tif a == \"--help\" || a == \"-h\" {\n")
	b.WriteString("\t\t\tfmt.Fprint(os.Stderr, settings.GenerateFullHelp())\n")
	b.WriteString("\t\t\tos.Exit(0)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tvar prompt string\n")
	b.WriteString("\tif promptFilePath != \"\" {\n")
	b.WriteString("\t\tdata, err := os.ReadFile(promptFilePath)\n")
	b.WriteString("\t\tos.Remove(promptFilePath)\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"weave: read prompt file: %v\\n\", err)\n")
	b.WriteString("\t\t\tos.Exit(1)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tprompt = string(data)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tb := bus.New()\n")
	b.WriteString("\tdefer b.Close()\n\n")
	b.WriteString("\tendCh := make(chan sdk.Event, 1)\n")
	b.WriteString("\tb.On(\"agent.end\", func(e sdk.Event) error {\n")
	b.WriteString("\t\tselect {\n")
	b.WriteString("\t\tcase endCh <- e:\n")
	b.WriteString("\t\tdefault:\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t})\n\n")
	b.WriteString("\tvar cfg sdk.Config\n")
	b.WriteString("\tfullCfg, cfgErr := settings.LoadFullConfig(cfgPath)\n")
	b.WriteString("\tif cfgErr != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: load config: %v\\n\", cfgErr)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcfg = fullCfg\n")
	b.WriteString("\tfullCfg.SetArgs(filtered)\n")
	b.WriteString("\tif projectDir != \"\" {\n")
	b.WriteString("\t\tfullCfg.SetProjectDir(projectDir)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif cfgPath != \"\" {\n")
	b.WriteString("\t\tsettings.EnsureLocalSettingsExcluded(settings.ProjectDirFromConfig(cfgPath))\n")
	b.WriteString("\t}\n")
	b.WriteString("\theadless := false\n")
	b.WriteString("\tif headlessFlag != \"\" {\n")
	b.WriteString("\t\tif parsed, err := strconv.ParseBool(headlessFlag); err == nil {\n")
	b.WriteString("\t\t\theadless = parsed\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcfg = sdk.HeadlessConfig{Config: cfg, Headless: headless}\n\n")
	b.WriteString("\t// Setup file logging\n")
	b.WriteString("\thomeDir, err := os.UserHomeDir()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: get home directory: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tlogDir := filepath.Join(homeDir, \".weave\", \"logs\")\n")
	b.WriteString("\tlogFile := filepath.Join(logDir, \"weave.log\")\n")
	b.WriteString("\tdebug := false\n")
	b.WriteString("\tif debugFlag != \"\" {\n")
	b.WriteString("\t\tif parsed, err := strconv.ParseBool(debugFlag); err == nil {\n")
	b.WriteString("\t\t\tdebug = parsed\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif os.Getenv(\"WEAVE_DEBUG\") == \"1\" || os.Getenv(\"WEAVE_DEBUG\") == \"true\" {\n")
	b.WriteString("\t\tdebug = true\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar extraWriters []io.Writer\n")
	b.WriteString("\tif headless {\n")
	b.WriteString("\t\textraWriters = append(extraWriters, os.Stderr)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := log.Setup(logFile, debug, extraWriters...); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: setup logging: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	optExtNames := make([]string, 0, len(exts))
	for _, ext := range exts {
		optExtNames = append(optExtNames, `"`+ext.Name+`"`)
	}

	b.WriteString("\tvar optExts []string\n")

	if len(optExtNames) > 0 {
		b.WriteString("\toptExts = []string{" + strings.Join(optExtNames, ", ") + "}\n")
	}

	b.WriteString("\n")
	b.WriteString("\tcore := wire.CoreWireConfig{AgentLoop: " + strconv.Quote(agentLoop) + "}\n")
	b.WriteString("\tif agentLoopName != \"\" {\n")
	b.WriteString("\t\tcore.AgentLoop = agentLoopName\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif prompt != \"\" {\n")
	b.WriteString("\t\tcore.SingleTurn = true\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif continueFlag != \"\" {\n")
	b.WriteString("\t\tif parsed, err := strconv.ParseBool(continueFlag); err == nil {\n")
	b.WriteString("\t\t\tcore.Continue = parsed\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"weave: invalid --weave-continue value %q\\n\", continueFlag)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif resumeID != \"\" {\n")
	b.WriteString("\t\tcore.Resume = resumeID\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif subagentID != \"\" {\n")
	b.WriteString("\t\tos.Setenv(\"WEAVE_SUBAGENT_ID\", subagentID)\n")
	b.WriteString("\t} else {\n")
	b.WriteString("\t\tos.Unsetenv(\"WEAVE_SUBAGENT_ID\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif messaging != \"\" {\n")
	b.WriteString("\t\tos.Setenv(\"WEAVE_MESSAGING\", messaging)\n")
	b.WriteString("\t} else {\n")
	b.WriteString("\t\tos.Unsetenv(\"WEAVE_MESSAGING\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif toolsSet {\n")
	b.WriteString("\t\tvar toolNames []string\n")
	b.WriteString("\t\tif toolsList != \"\" {\n")
	b.WriteString("\t\t\ttoolNames = strings.Split(toolsList, \",\")\n")
	b.WriteString("\t\t\tfor i := range toolNames {\n")
	b.WriteString("\t\t\t\ttoolNames[i] = strings.TrimSpace(toolNames[i])\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\ttoolNames = []string{}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tsdk.SetToolFilter(toolNames)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif sandboxMode != \"\" {\n")
	b.WriteString("\t\tos.Setenv(\"WEAVE_SANDBOX_MODE\", sandboxMode)\n")
	b.WriteString("\t}\n")
	b.WriteString("\twired, err := wire.WireWithCore(core, optExts, b, cfg)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\n")
	b.WriteString("\tjsonOut := &syncWriter{w: os.Stdout}\n")
	b.WriteString("\tvar jsonQueue chan map[string]any\n")
	b.WriteString("\tvar jsonWg sync.WaitGroup\n")

	b.WriteString("\tb.Publish(sdk.NewEvent(\"output.redirect\", sdk.OutputRedirectPayload{Writer: jsonOut}))\n")
	b.WriteString("\n")
	b.WriteString("\tif outputMode == \"json\" {\n")
	b.WriteString("\t\tjsonQueue = make(chan map[string]any, 10000)\n")
	b.WriteString("\t\tjsonWg.Add(1)\n")
	b.WriteString("\t\tgo func() {\n")
	b.WriteString("\t\t\tdefer jsonWg.Done()\n")
	b.WriteString("\t\t\tfor payload := range jsonQueue {\n")
	b.WriteString("\t\t\t\tif data, err := json.Marshal(payload); err == nil {\n")
	b.WriteString("\t\t\t\t\tfmt.Fprintln(jsonOut, string(data))\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}()\n")
	b.WriteString("\t\tb.OnAll(func(e sdk.Event) error {\n")
	b.WriteString("\t\t\tvar payload map[string]any\n")
	b.WriteString("\t\t\tswitch e.Topic {\n")
	b.WriteString("\t\t\tcase \"agent.message_start\":\n")
	b.WriteString("\t\t\t\tpayload = map[string]any{\"type\": \"message_start\"}\n")
	b.WriteString("\t\t\t\tif m, ok := e.Payload.(string); ok && m != \"\" {\n")
	b.WriteString("\t\t\t\t\tpayload[\"model\"] = m\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tcase \"agent.message_update\":\n")
	b.WriteString("\t\t\t\tpayload = map[string]any{\"type\": \"message_update\"}\n")
	b.WriteString("\t\t\t\tif s, ok := e.Payload.(string); ok {\n")
	b.WriteString("\t\t\t\t\tpayload[\"content\"] = s\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tcase \"agent.tool_call\":\n")
	b.WriteString("\t\t\t\tpayload = map[string]any{\"type\": \"tool_call\"}\n")
	b.WriteString("\t\t\t\tif m, ok := e.Payload.(map[string]any); ok {\n")
	b.WriteString("\t\t\t\t\tpayload[\"tool\"] = m[\"tool\"]\n")
	b.WriteString("\t\t\t\t\tpayload[\"args\"] = m[\"args\"]\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tcase \"agent.tool_result\":\n")
	b.WriteString("\t\t\t\tpayload = map[string]any{\"type\": \"tool_result\"}\n")
	b.WriteString("\t\t\t\tif m, ok := e.Payload.(map[string]any); ok {\n")
	b.WriteString("\t\t\t\t\tpayload[\"tool\"] = m[\"tool\"]\n")
	b.WriteString("\t\t\t\t\tif result, ok := m[\"result\"].(sdk.ToolResult); ok {\n")
	b.WriteString("\t\t\t\t\t\tpayload[\"output\"] = result.Content\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tcase \"agent.message_end\":\n")
	b.WriteString("\t\t\t\tpayload = map[string]any{\"type\": \"message_end\"}\n")
	b.WriteString("\t\t\t\tif m, ok := e.Payload.(map[string]any); ok {\n")
	b.WriteString("\t\t\t\t\tpayload[\"content\"] = m[\"content\"]\n")
	b.WriteString("\t\t\t\t\tif thinking, ok := m[\"thinking\"].(string); ok && thinking != \"\" {\n")
	b.WriteString("\t\t\t\t\t\tpayload[\"thinking\"] = thinking\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\treturn nil\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tjsonQueue <- payload\n")
	b.WriteString("\t\t\treturn nil\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif modelOverride != \"\" {\n")
	b.WriteString("\t\tpayload := map[string]string{\"model\": modelOverride}\n")
	b.WriteString("\t\tif m, ok := model.GetModel(modelOverride); ok && m.Provider != \"\" && model.ModelProviderCount(modelOverride) == 1 {\n")
	b.WriteString("\t\t\tpayload[\"provider\"] = m.Provider\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tb.Publish(sdk.NewEvent(\"model.change\", payload))\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif prompt != \"\" {\n")
	b.WriteString("\t\tif core.Continue || core.Resume != \"\" {\n")
	b.WriteString("\t\t\tb.Publish(sdk.NewEvent(\"agent.followup\", prompt))\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tb.Publish(sdk.NewEvent(\"agent.prompt\", prompt))\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsig := make(chan os.Signal, 1)\n")
	b.WriteString("\tsignal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)\n")
	b.WriteString("\tvar endErr string\n")
	b.WriteString("\tselect {\n")
	b.WriteString("\tcase <-sig:\n")
	b.WriteString("\tcase evt := <-endCh:\n")
	b.WriteString("\t\tif s, ok := evt.Payload.(string); ok && s != \"\" {\n")
	b.WriteString("\t\t\tendErr = s\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := wired.Close(); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: shutdown error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := b.Close(); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: bus close error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif jsonQueue != nil {\n")
	b.WriteString("\t\tclose(jsonQueue)\n")
	b.WriteString("\t\tjsonWg.Wait()\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif endErr != \"\" {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: %s\\n\", endErr)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("generate main.go: %w", err)
	}

	return nil
}

// Build generates go.mod and main.go in dir, runs go build, and returns the binary path.
// moduleRoot is the absolute path to the weave module root (containing go.mod).
// agentLoop identifies the core agent loop extension for WireWithCore.
// When headless is true, UI extensions (IsUIExt) are excluded from compilation.
// Extensions are sorted by name to match the hash computation order.
func Build(dir, moduleRoot, moduleVersion, agentLoop string, headless bool, exts []ExtensionInfo) (string, error) {
	sorted := make([]ExtensionInfo, len(exts))
	copy(sorted, exts)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	// Filter out UI extensions in headless mode before generating go.mod/main.go.
	if headless {
		filtered := make([]ExtensionInfo, 0, len(sorted))
		for _, ext := range sorted {
			if !ext.IsUIExt {
				filtered = append(filtered, ext)
			}
		}

		sorted = filtered
	}

	// Ensure each extension dir has a go.mod so Go treats it as a module
	for _, ext := range sorted {
		if err := ensureExtGoMod(ext, moduleRoot, moduleVersion); err != nil {
			return "", fmt.Errorf("build: extension %s go.mod: %w", ext.Name, err)
		}
	}

	// Read actual module paths from extension go.mods
	for i := range sorted {
		sorted[i].ModulePath = readModulePath(sorted[i].Dir)
	}

	if err := GenerateGoMod(dir, moduleRoot, moduleVersion, sorted); err != nil {
		return "", fmt.Errorf("build: generate go.mod: %w", err)
	}

	if err := GenerateMainGo(dir, sorted, agentLoop); err != nil {
		return "", fmt.Errorf("build: generate main.go: %w", err)
	}

	fmt.Fprintf(os.Stderr, "  -> resolving dependencies...\n")

	tidyCmd := exec.CommandContext(context.Background(), "go", "mod", "tidy")

	tidyCmd.Dir = dir
	if output, err := tidyCmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build: go mod tidy: %w\n%s", err, output)
	}

	fmt.Fprintf(os.Stderr, "  -> compiling...\n")

	binaryPath := filepath.Join(dir, "weave")
	cmd := exec.CommandContext(context.Background(), "go", "build", "-o", binaryPath, ".")

	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build: go build: %w\n%s", err, output)
	}

	return binaryPath, nil
}

// ensureExtGoMod writes a go.mod in the extension dir only if one does not
// already exist. Extensions that ship their own go.mod (with external
// dependencies, toolchain directives, etc.) are left intact.
// Shim go.mods (identified by a sentinel comment) are always regenerated
// so the absolute replace directive stays current after repo moves.
const shimSentinel = "// Code generated by weave launcher. DO NOT EDIT.\n"

func ensureExtGoMod(ext ExtensionInfo, moduleRoot, moduleVersion string) error {
	goModPath := filepath.Join(ext.Dir, "go.mod")

	if data, err := os.ReadFile(goModPath); err == nil {
		if !strings.HasPrefix(string(data), shimSentinel) {
			return nil
		}
	}

	var content string
	if moduleRoot != "" {
		content = shimSentinel + "module github.com/weave-agent/weave/ext/" + ext.Name + "\n\n" + goVersion() + "\n\nrequire github.com/weave-agent/weave v0.0.0\n\nreplace github.com/weave-agent/weave => " + moduleRoot + "\n"
	} else {
		content = shimSentinel + "module github.com/weave-agent/weave/ext/" + ext.Name + "\n\n" + goVersion() + "\n\nrequire github.com/weave-agent/weave " + moduleVersion + "\n\n"
	}

	if err := os.WriteFile(goModPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("ensure extension go.mod: %w", err)
	}

	return nil
}
