package launcher

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"hash"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"sort"
	"strings"
)

// ComputeHash returns a deterministic SHA256 hex string for the given extensions.
// The hash covers the Go version, the root module's go.mod and go.sum, the sorted
// contents of all extension .go files, and the contents of any additional core
// package directories.
func ComputeHash(exts []ExtensionInfo, moduleRoot string, coreDirs ...string) (string, error) {
	h := sha256.New()

	h.Write([]byte("go" + runtime.Version() + "\n"))

	HashModuleGraph(h, moduleRoot)

	sorted := make([]ExtensionInfo, len(exts))
	copy(sorted, exts)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	for _, ext := range sorted {
		h.Write([]byte("ext:" + ext.Name + "\n"))

		for _, f := range ext.GoFiles {
			rel, relErr := filepath.Rel(ext.Dir, f)
			if relErr != nil {
				rel = f
			}

			h.Write([]byte(rel + "\n"))

			data, err := os.ReadFile(f)
			if err != nil {
				return "", fmt.Errorf("hash: read %s: %w", f, err)
			}

			h.Write(data)
		}

		goModPath := filepath.Join(ext.Dir, "go.mod")
		if data, err := os.ReadFile(goModPath); err == nil {
			// Skip shim go.mods generated by ensureExtGoMod — they are
			// build artifacts, not extension inputs.
			if !strings.HasPrefix(string(data), shimSentinel) {
				h.Write([]byte("go.mod\n"))
				h.Write(data)

				goSumPath := filepath.Join(ext.Dir, "go.sum")
				if sumData, sumErr := os.ReadFile(goSumPath); sumErr == nil {
					h.Write([]byte("go.sum\n"))
					h.Write(sumData)
				}
			}
		}
	}

	for _, dir := range coreDirs {
		if err := hashDir(h, dir); err != nil {
			return "", fmt.Errorf("hash: core dir %s: %w", dir, err)
		}
	}

	// Hash transitive local dependencies discovered from extension go.mod files.
	// These are shared libraries (e.g. openai-compat) that extensions depend on
	// via replace directives. Without this, changes to shared libs don't
	// invalidate the cache.
	transitiveSeen := make(map[string]bool)

	for _, ext := range sorted {
		for depModPath, depDir := range readLocalReplaces(ext.Dir) {
			if transitiveSeen[depDir] {
				continue
			}

			transitiveSeen[depDir] = true

			h.Write([]byte("transitive:" + depModPath + "\n"))

			if err := hashDir(h, depDir); err != nil {
				return "", fmt.Errorf("hash: transitive dep %s: %w", depDir, err)
			}
		}
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}

// HashModuleGraph writes the root go.mod and go.sum contents into the hash,
// so changes to the module graph (dependency versions, toolchain directives)
// invalidate the cache even when no .go files changed.
func HashModuleGraph(h hash.Hash, moduleRoot string) {
	for _, name := range []string{"go.mod", "go.sum"} {
		data, err := os.ReadFile(filepath.Join(moduleRoot, name))
		if err != nil {
			continue
		}

		h.Write([]byte(name + "\n"))
		h.Write(data)
	}
}

func hashDir(h hash.Hash, dir string) error {
	var files []string

	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			return nil
		}

		name := d.Name()
		if (strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")) || name == "go.mod" || name == "go.sum" {
			files = append(files, path)
		}

		return nil
	})
	if err != nil {
		return fmt.Errorf("walk dir: %w", err)
	}

	sort.Strings(files)

	for _, f := range files {
		rel, relErr := filepath.Rel(dir, f)
		if relErr != nil {
			rel = f
		}

		h.Write([]byte(rel + "\n"))

		data, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("read %s: %w", f, err)
		}

		h.Write(data)
	}

	return nil
}

// goVersion returns the Go version string for go.mod (e.g. "go 1.22.0").
func goVersion() string {
	// runtime.Version() returns e.g. "go1.22.0", "go1.22.0 X:loopvar", "go1.26.2-X:jsonv2"
	v := strings.TrimPrefix(runtime.Version(), "go")
	// Strip anything after a space or dash that isn't a digit/dot
	if idx := strings.IndexFunc(v, func(r rune) bool {
		return !strings.ContainsRune("0123456789.", r)
	}); idx != -1 {
		v = v[:idx]
	}

	return "go " + v
}

// extModulePath returns the module path for an extension, reading it from
// the extension's go.mod. Falls back to "weave/ext/{name}" if unavailable.
func extModulePath(ext ExtensionInfo) string {
	if ext.ModulePath != "" {
		return ext.ModulePath
	}

	return "weave/ext/" + ext.Name
}

// readModulePath reads the module path from a go.mod file in dir.
func readModulePath(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return ""
	}

	for line := range strings.SplitSeq(string(data), "\n") {
		if after, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.TrimSpace(after)
		}
	}

	return ""
}

// GenerateGoMod creates a go.mod file for the built binary.
// moduleRoot is the path to the weave module root (containing go.mod).
func GenerateGoMod(dir, moduleRoot string, exts []ExtensionInfo) error {
	var b strings.Builder
	b.WriteString("module weave-built\n\n")
	b.WriteString(goVersion() + "\n\n")
	b.WriteString("require (\n")
	b.WriteString("\tweave v0.0.0\n")

	for _, ext := range exts {
		b.WriteString("\t" + extModulePath(ext) + " v0.0.0\n")
	}

	// Propagate transitive local dependencies from extension go.mod files.
	directModulePaths := make(map[string]bool)

	directModulePaths["weave"] = true
	for _, ext := range exts {
		directModulePaths[extModulePath(ext)] = true
	}

	var (
		extraRequires []string
		extraReplaces []string
	)

	for _, ext := range exts {
		localReplaces := readLocalReplaces(ext.Dir)
		for modPath, localPath := range localReplaces {
			if directModulePaths[modPath] {
				continue
			}

			directModulePaths[modPath] = true
			extraRequires = append(extraRequires, modPath+" v0.0.0")
			extraReplaces = append(extraReplaces, "replace "+modPath+" => "+localPath)
		}
	}

	for _, req := range extraRequires {
		b.WriteString("\t" + req + "\n")
	}

	b.WriteString(")\n\n")
	b.WriteString("replace weave => " + moduleRoot + "\n")

	for _, ext := range exts {
		b.WriteString("replace " + extModulePath(ext) + " => " + ext.Dir + "\n")
	}

	for _, rep := range extraReplaces {
		b.WriteString(rep + "\n")
	}

	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("generate go.mod: %w", err)
	}

	return nil
}

// readLocalReplaces parses a go.mod file and returns replace directives that
// point to local paths (relative or absolute). The returned map keys are
// module paths and values are resolved absolute paths.
func readLocalReplaces(dir string) map[string]string {
	data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return nil
	}

	result := make(map[string]string)
	inReplaceBlock := false

	for line := range strings.SplitSeq(string(data), "\n") {
		trimmed := strings.TrimSpace(line)

		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			continue
		}

		if strings.HasPrefix(trimmed, "replace ") {
			if strings.Contains(trimmed, "=>") {
				parseSingleReplace(trimmed[len("replace "):], dir, result)
			} else {
				inReplaceBlock = true
			}

			continue
		}

		if inReplaceBlock {
			if trimmed == ")" {
				inReplaceBlock = false

				continue
			}

			if strings.Contains(trimmed, "=>") {
				parseSingleReplace(trimmed, dir, result)
			}
		}
	}

	return result
}

func parseSingleReplace(s, dir string, result map[string]string) {
	before, after, ok := strings.Cut(s, "=>")
	if !ok {
		return
	}

	modPath := strings.TrimSpace(before)
	localPath := strings.TrimSpace(after)

	if localPath == "" {
		return
	}

	// Only capture local paths (relative or absolute), not version queries.
	if !strings.HasPrefix(localPath, ".") && !strings.HasPrefix(localPath, "/") {
		return
	}

	absPath := localPath
	if !strings.HasPrefix(localPath, "/") {
		absPath = filepath.Join(dir, localPath)
	}

	result[modPath] = absPath
}

// GenerateMainGo creates a main.go that creates a bus, wires all extensions, and blocks on signal.
// The generated binary accepts:
//   - --weave-config=<path> to pass config to extensions
//   - --weave-prompt-file=<path> to read the initial prompt from a file
//   - --weave-agent-loop=<name> and --weave-providers=<name1,name2> for core wiring
func GenerateMainGo(dir string, exts []ExtensionInfo, agentLoop string, providers []string) error {
	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/signal\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"syscall\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"weave/bus\"\n")
	b.WriteString("\t\"weave/sdk\"\n")

	for _, ext := range exts {
		b.WriteString("\n")
		b.WriteString("\t_ \"" + extModulePath(ext) + "\"\n")
	}

	b.WriteString(")\n\n")
	b.WriteString("func main() {\n")
	b.WriteString("\tvar cfgPath string\n")
	b.WriteString("\tvar promptFilePath string\n")
	b.WriteString("\tvar agentLoopName string\n")
	b.WriteString("\tvar providersFlag string\n")
	b.WriteString("\tfiltered := make([]string, 0, len(os.Args)-1)\n")
	b.WriteString("\tfor _, a := range os.Args[1:] {\n")
	b.WriteString("\t\tif p, ok := strings.CutPrefix(a, \"--weave-config=\"); ok {\n")
	b.WriteString("\t\t\tcfgPath = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-prompt-file=\"); ok {\n")
	b.WriteString("\t\t\tpromptFilePath = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-agent-loop=\"); ok {\n")
	b.WriteString("\t\t\tagentLoopName = p\n")
	b.WriteString("\t\t} else if p, ok := strings.CutPrefix(a, \"--weave-providers=\"); ok {\n")
	b.WriteString("\t\t\tprovidersFlag = p\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tfiltered = append(filtered, a)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tos.Args = append([]string{os.Args[0]}, filtered...)\n\n")
	b.WriteString("\tvar prompt string\n")
	b.WriteString("\tif promptFilePath != \"\" {\n")
	b.WriteString("\t\tdata, err := os.ReadFile(promptFilePath)\n")
	b.WriteString("\t\tos.Remove(promptFilePath)\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"weave: read prompt file: %v\\n\", err)\n")
	b.WriteString("\t\t\tos.Exit(1)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tprompt = string(data)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tb := bus.New()\n")
	b.WriteString("\tdefer b.Close()\n\n")
	b.WriteString("\tendCh := b.Subscribe(\"agent.end\")\n\n")
	b.WriteString("\tvar cfg sdk.Config\n")
	b.WriteString("\tif cfgPath != \"\" {\n")
	b.WriteString("\t\tcfg = sdk.FilePathConfig(cfgPath)\n")
	b.WriteString("\t}\n\n")

	optExtNames := make([]string, 0, len(exts))
	for _, ext := range exts {
		// Core extensions (agent-loop, providers) are handled by WireWithCore,
		// not passed as optional extensions.
		if ext.Name == agentLoop || slices.Contains(providers, ext.Name) {
			continue
		}

		optExtNames = append(optExtNames, `"`+ext.Name+`"`)
	}

	providerNames := make([]string, len(providers))
	for i, p := range providers {
		providerNames[i] = `"` + p + `"`
	}

	b.WriteString("\tvar optExts []string\n")

	if len(optExtNames) > 0 {
		b.WriteString("\toptExts = []string{" + strings.Join(optExtNames, ", ") + "}\n")
	}

	b.WriteString("\n")
	b.WriteString("\tcore := sdk.CoreWireConfig{AgentLoop: \"" + agentLoop + "\", Providers: []string{" + strings.Join(providerNames, ", ") + "}}\n")
	b.WriteString("\tif agentLoopName != \"\" {\n")
	b.WriteString("\t\tcore.AgentLoop = agentLoopName\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif providersFlag != \"\" {\n")
	b.WriteString("\t\tcore.Providers = strings.Split(providersFlag, \",\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\twired, err := sdk.WireWithCore(core, optExts, b, cfg)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tif prompt != \"\" {\n")
	b.WriteString("\t\tb.Publish(sdk.NewEvent(\"agent.prompt\", prompt))\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tsig := make(chan os.Signal, 1)\n")
	b.WriteString("\tsignal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)\n")
	b.WriteString("\tvar endErr string\n")
	b.WriteString("\tselect {\n")
	b.WriteString("\tcase <-sig:\n")
	b.WriteString("\tcase evt := <-endCh:\n")
	b.WriteString("\t\tif s, ok := evt.Payload.(string); ok && s != \"\" {\n")
	b.WriteString("\t\t\tendErr = s\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := wired.Close(); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: shutdown error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif endErr != \"\" {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"weave: %s\\n\", endErr)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("generate main.go: %w", err)
	}

	return nil
}

// Build generates go.mod and main.go in dir, runs go build, and returns the binary path.
// moduleRoot is the absolute path to the weave module root (containing go.mod).
// agentLoop and providers identify the core extensions for WireWithCore.
// Extensions are sorted by name to match the hash computation order.
func Build(dir, moduleRoot, agentLoop string, providers []string, exts []ExtensionInfo) (string, error) {
	sorted := make([]ExtensionInfo, len(exts))
	copy(sorted, exts)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	// Ensure each extension dir has a go.mod so Go treats it as a module
	for _, ext := range sorted {
		if err := ensureExtGoMod(ext, moduleRoot); err != nil {
			return "", fmt.Errorf("build: extension %s go.mod: %w", ext.Name, err)
		}
	}

	// Read actual module paths from extension go.mods
	for i := range sorted {
		sorted[i].ModulePath = readModulePath(sorted[i].Dir)
	}

	if err := GenerateGoMod(dir, moduleRoot, sorted); err != nil {
		return "", fmt.Errorf("build: generate go.mod: %w", err)
	}

	if err := GenerateMainGo(dir, sorted, agentLoop, providers); err != nil {
		return "", fmt.Errorf("build: generate main.go: %w", err)
	}

	tidyCmd := exec.CommandContext(context.Background(), "go", "mod", "tidy")

	tidyCmd.Dir = dir
	if output, err := tidyCmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build: go mod tidy: %w\n%s", err, output)
	}

	binaryPath := filepath.Join(dir, "weave")
	cmd := exec.CommandContext(context.Background(), "go", "build", "-o", binaryPath, ".")

	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build: go build: %w\n%s", err, output)
	}

	return binaryPath, nil
}

// ensureExtGoMod writes a go.mod in the extension dir only if one does not
// already exist. Extensions that ship their own go.mod (with external
// dependencies, toolchain directives, etc.) are left intact.
// Shim go.mods (identified by a sentinel comment) are always regenerated
// so the absolute replace directive stays current after repo moves.
const shimSentinel = "// Code generated by weave launcher. DO NOT EDIT.\n"

func ensureExtGoMod(ext ExtensionInfo, moduleRoot string) error {
	goModPath := filepath.Join(ext.Dir, "go.mod")

	if data, err := os.ReadFile(goModPath); err == nil {
		if !strings.HasPrefix(string(data), shimSentinel) {
			return nil
		}
	}

	content := shimSentinel + "module weave/ext/" + ext.Name + "\n\n" + goVersion() + "\n\nrequire weave v0.0.0\n\nreplace weave => " + moduleRoot + "\n"

	if err := os.WriteFile(goModPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("ensure extension go.mod: %w", err)
	}

	return nil
}
