// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sdk

import (
	"sync"
)

// Ensure, that ConfigMock does implement Config.
// If this is not the case, regenerate this file with moq.
var _ Config = &ConfigMock{}

// ConfigMock is a mock implementation of Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked Config
//		mockedConfig := &ConfigMock{
//			ExtensionConfigFunc: func(scope string, name string, target any, envPrefix string) error {
//				panic("mock out the ExtensionConfig method")
//			},
//			FilePathFunc: func() string {
//				panic("mock out the FilePath method")
//			},
//			IsHeadlessFunc: func() bool {
//				panic("mock out the IsHeadless method")
//			},
//			PreferencesFunc: func(target any) error {
//				panic("mock out the Preferences method")
//			},
//			ProjectDirFunc: func() string {
//				panic("mock out the ProjectDir method")
//			},
//			ResolveKeyFunc: func(providerName string, envVar string) (string, error) {
//				panic("mock out the ResolveKey method")
//			},
//			RespectGitignoreFunc: func() bool {
//				panic("mock out the RespectGitignore method")
//			},
//			SavePreferencesFunc: func(target any) error {
//				panic("mock out the SavePreferences method")
//			},
//			SaveProviderKeyFunc: func(providerName string, apiKey string) error {
//				panic("mock out the SaveProviderKey method")
//			},
//		}
//
//		// use mockedConfig in code that requires Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// ExtensionConfigFunc mocks the ExtensionConfig method.
	ExtensionConfigFunc func(scope string, name string, target any, envPrefix string) error

	// FilePathFunc mocks the FilePath method.
	FilePathFunc func() string

	// IsHeadlessFunc mocks the IsHeadless method.
	IsHeadlessFunc func() bool

	// PreferencesFunc mocks the Preferences method.
	PreferencesFunc func(target any) error

	// ProjectDirFunc mocks the ProjectDir method.
	ProjectDirFunc func() string

	// ResolveKeyFunc mocks the ResolveKey method.
	ResolveKeyFunc func(providerName string, envVar string) (string, error)

	// RespectGitignoreFunc mocks the RespectGitignore method.
	RespectGitignoreFunc func() bool

	// SavePreferencesFunc mocks the SavePreferences method.
	SavePreferencesFunc func(target any) error

	// SaveProviderKeyFunc mocks the SaveProviderKey method.
	SaveProviderKeyFunc func(providerName string, apiKey string) error

	// calls tracks calls to the methods.
	calls struct {
		// ExtensionConfig holds details about calls to the ExtensionConfig method.
		ExtensionConfig []struct {
			// Scope is the scope argument value.
			Scope string
			// Name is the name argument value.
			Name string
			// Target is the target argument value.
			Target any
			// EnvPrefix is the envPrefix argument value.
			EnvPrefix string
		}
		// FilePath holds details about calls to the FilePath method.
		FilePath []struct {
		}
		// IsHeadless holds details about calls to the IsHeadless method.
		IsHeadless []struct {
		}
		// Preferences holds details about calls to the Preferences method.
		Preferences []struct {
			// Target is the target argument value.
			Target any
		}
		// ProjectDir holds details about calls to the ProjectDir method.
		ProjectDir []struct {
		}
		// ResolveKey holds details about calls to the ResolveKey method.
		ResolveKey []struct {
			// ProviderName is the providerName argument value.
			ProviderName string
			// EnvVar is the envVar argument value.
			EnvVar string
		}
		// RespectGitignore holds details about calls to the RespectGitignore method.
		RespectGitignore []struct {
		}
		// SavePreferences holds details about calls to the SavePreferences method.
		SavePreferences []struct {
			// Target is the target argument value.
			Target any
		}
		// SaveProviderKey holds details about calls to the SaveProviderKey method.
		SaveProviderKey []struct {
			// ProviderName is the providerName argument value.
			ProviderName string
			// ApiKey is the apiKey argument value.
			ApiKey string
		}
	}
	lockExtensionConfig  sync.RWMutex
	lockFilePath         sync.RWMutex
	lockIsHeadless       sync.RWMutex
	lockPreferences      sync.RWMutex
	lockProjectDir       sync.RWMutex
	lockResolveKey       sync.RWMutex
	lockRespectGitignore sync.RWMutex
	lockSavePreferences  sync.RWMutex
	lockSaveProviderKey  sync.RWMutex
}

// ExtensionConfig calls ExtensionConfigFunc.
func (mock *ConfigMock) ExtensionConfig(scope string, name string, target any, envPrefix string) error {
	callInfo := struct {
		Scope     string
		Name      string
		Target    any
		EnvPrefix string
	}{
		Scope:     scope,
		Name:      name,
		Target:    target,
		EnvPrefix: envPrefix,
	}
	mock.lockExtensionConfig.Lock()
	mock.calls.ExtensionConfig = append(mock.calls.ExtensionConfig, callInfo)
	mock.lockExtensionConfig.Unlock()
	if mock.ExtensionConfigFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ExtensionConfigFunc(scope, name, target, envPrefix)
}

// ExtensionConfigCalls gets all the calls that were made to ExtensionConfig.
// Check the length with:
//
//	len(mockedConfig.ExtensionConfigCalls())
func (mock *ConfigMock) ExtensionConfigCalls() []struct {
	Scope     string
	Name      string
	Target    any
	EnvPrefix string
} {
	var calls []struct {
		Scope     string
		Name      string
		Target    any
		EnvPrefix string
	}
	mock.lockExtensionConfig.RLock()
	calls = mock.calls.ExtensionConfig
	mock.lockExtensionConfig.RUnlock()
	return calls
}

// FilePath calls FilePathFunc.
func (mock *ConfigMock) FilePath() string {
	callInfo := struct {
	}{}
	mock.lockFilePath.Lock()
	mock.calls.FilePath = append(mock.calls.FilePath, callInfo)
	mock.lockFilePath.Unlock()
	if mock.FilePathFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.FilePathFunc()
}

// FilePathCalls gets all the calls that were made to FilePath.
// Check the length with:
//
//	len(mockedConfig.FilePathCalls())
func (mock *ConfigMock) FilePathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFilePath.RLock()
	calls = mock.calls.FilePath
	mock.lockFilePath.RUnlock()
	return calls
}

// IsHeadless calls IsHeadlessFunc.
func (mock *ConfigMock) IsHeadless() bool {
	callInfo := struct {
	}{}
	mock.lockIsHeadless.Lock()
	mock.calls.IsHeadless = append(mock.calls.IsHeadless, callInfo)
	mock.lockIsHeadless.Unlock()
	if mock.IsHeadlessFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.IsHeadlessFunc()
}

// IsHeadlessCalls gets all the calls that were made to IsHeadless.
// Check the length with:
//
//	len(mockedConfig.IsHeadlessCalls())
func (mock *ConfigMock) IsHeadlessCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsHeadless.RLock()
	calls = mock.calls.IsHeadless
	mock.lockIsHeadless.RUnlock()
	return calls
}

// Preferences calls PreferencesFunc.
func (mock *ConfigMock) Preferences(target any) error {
	callInfo := struct {
		Target any
	}{
		Target: target,
	}
	mock.lockPreferences.Lock()
	mock.calls.Preferences = append(mock.calls.Preferences, callInfo)
	mock.lockPreferences.Unlock()
	if mock.PreferencesFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PreferencesFunc(target)
}

// PreferencesCalls gets all the calls that were made to Preferences.
// Check the length with:
//
//	len(mockedConfig.PreferencesCalls())
func (mock *ConfigMock) PreferencesCalls() []struct {
	Target any
} {
	var calls []struct {
		Target any
	}
	mock.lockPreferences.RLock()
	calls = mock.calls.Preferences
	mock.lockPreferences.RUnlock()
	return calls
}

// ProjectDir calls ProjectDirFunc.
func (mock *ConfigMock) ProjectDir() string {
	callInfo := struct {
	}{}
	mock.lockProjectDir.Lock()
	mock.calls.ProjectDir = append(mock.calls.ProjectDir, callInfo)
	mock.lockProjectDir.Unlock()
	if mock.ProjectDirFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.ProjectDirFunc()
}

// ProjectDirCalls gets all the calls that were made to ProjectDir.
// Check the length with:
//
//	len(mockedConfig.ProjectDirCalls())
func (mock *ConfigMock) ProjectDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjectDir.RLock()
	calls = mock.calls.ProjectDir
	mock.lockProjectDir.RUnlock()
	return calls
}

// ResolveKey calls ResolveKeyFunc.
func (mock *ConfigMock) ResolveKey(providerName string, envVar string) (string, error) {
	callInfo := struct {
		ProviderName string
		EnvVar       string
	}{
		ProviderName: providerName,
		EnvVar:       envVar,
	}
	mock.lockResolveKey.Lock()
	mock.calls.ResolveKey = append(mock.calls.ResolveKey, callInfo)
	mock.lockResolveKey.Unlock()
	if mock.ResolveKeyFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.ResolveKeyFunc(providerName, envVar)
}

// ResolveKeyCalls gets all the calls that were made to ResolveKey.
// Check the length with:
//
//	len(mockedConfig.ResolveKeyCalls())
func (mock *ConfigMock) ResolveKeyCalls() []struct {
	ProviderName string
	EnvVar       string
} {
	var calls []struct {
		ProviderName string
		EnvVar       string
	}
	mock.lockResolveKey.RLock()
	calls = mock.calls.ResolveKey
	mock.lockResolveKey.RUnlock()
	return calls
}

// RespectGitignore calls RespectGitignoreFunc.
func (mock *ConfigMock) RespectGitignore() bool {
	callInfo := struct {
	}{}
	mock.lockRespectGitignore.Lock()
	mock.calls.RespectGitignore = append(mock.calls.RespectGitignore, callInfo)
	mock.lockRespectGitignore.Unlock()
	if mock.RespectGitignoreFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.RespectGitignoreFunc()
}

// RespectGitignoreCalls gets all the calls that were made to RespectGitignore.
// Check the length with:
//
//	len(mockedConfig.RespectGitignoreCalls())
func (mock *ConfigMock) RespectGitignoreCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRespectGitignore.RLock()
	calls = mock.calls.RespectGitignore
	mock.lockRespectGitignore.RUnlock()
	return calls
}

// SavePreferences calls SavePreferencesFunc.
func (mock *ConfigMock) SavePreferences(target any) error {
	callInfo := struct {
		Target any
	}{
		Target: target,
	}
	mock.lockSavePreferences.Lock()
	mock.calls.SavePreferences = append(mock.calls.SavePreferences, callInfo)
	mock.lockSavePreferences.Unlock()
	if mock.SavePreferencesFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SavePreferencesFunc(target)
}

// SavePreferencesCalls gets all the calls that were made to SavePreferences.
// Check the length with:
//
//	len(mockedConfig.SavePreferencesCalls())
func (mock *ConfigMock) SavePreferencesCalls() []struct {
	Target any
} {
	var calls []struct {
		Target any
	}
	mock.lockSavePreferences.RLock()
	calls = mock.calls.SavePreferences
	mock.lockSavePreferences.RUnlock()
	return calls
}

// SaveProviderKey calls SaveProviderKeyFunc.
func (mock *ConfigMock) SaveProviderKey(providerName string, apiKey string) error {
	callInfo := struct {
		ProviderName string
		ApiKey       string
	}{
		ProviderName: providerName,
		ApiKey:       apiKey,
	}
	mock.lockSaveProviderKey.Lock()
	mock.calls.SaveProviderKey = append(mock.calls.SaveProviderKey, callInfo)
	mock.lockSaveProviderKey.Unlock()
	if mock.SaveProviderKeyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SaveProviderKeyFunc(providerName, apiKey)
}

// SaveProviderKeyCalls gets all the calls that were made to SaveProviderKey.
// Check the length with:
//
//	len(mockedConfig.SaveProviderKeyCalls())
func (mock *ConfigMock) SaveProviderKeyCalls() []struct {
	ProviderName string
	ApiKey       string
} {
	var calls []struct {
		ProviderName string
		ApiKey       string
	}
	mock.lockSaveProviderKey.RLock()
	calls = mock.calls.SaveProviderKey
	mock.lockSaveProviderKey.RUnlock()
	return calls
}
