// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sdk

import (
	"sync"
)

// Ensure, that ConfigMock does implement Config.
// If this is not the case, regenerate this file with moq.
var _ Config = &ConfigMock{}

// ConfigMock is a mock implementation of Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked Config
//		mockedConfig := &ConfigMock{
//			ExtensionConfigFunc: func(scope string, name string, target any) error {
//				panic("mock out the ExtensionConfig method")
//			},
//			FilePathFunc: func() string {
//				panic("mock out the FilePath method")
//			},
//			IsHeadlessFunc: func() bool {
//				panic("mock out the IsHeadless method")
//			},
//			ProjectDirFunc: func() string {
//				panic("mock out the ProjectDir method")
//			},
//			RespectGitignoreFunc: func() bool {
//				panic("mock out the RespectGitignore method")
//			},
//		}
//
//		// use mockedConfig in code that requires Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// ExtensionConfigFunc mocks the ExtensionConfig method.
	ExtensionConfigFunc func(scope string, name string, target any) error

	// FilePathFunc mocks the FilePath method.
	FilePathFunc func() string

	// IsHeadlessFunc mocks the IsHeadless method.
	IsHeadlessFunc func() bool

	// ProjectDirFunc mocks the ProjectDir method.
	ProjectDirFunc func() string

	// RespectGitignoreFunc mocks the RespectGitignore method.
	RespectGitignoreFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// ExtensionConfig holds details about calls to the ExtensionConfig method.
		ExtensionConfig []struct {
			// Scope is the scope argument value.
			Scope string
			// Name is the name argument value.
			Name string
			// Target is the target argument value.
			Target any
		}
		// FilePath holds details about calls to the FilePath method.
		FilePath []struct {
		}
		// IsHeadless holds details about calls to the IsHeadless method.
		IsHeadless []struct {
		}
		// ProjectDir holds details about calls to the ProjectDir method.
		ProjectDir []struct {
		}
		// RespectGitignore holds details about calls to the RespectGitignore method.
		RespectGitignore []struct {
		}
	}
	lockExtensionConfig  sync.RWMutex
	lockFilePath         sync.RWMutex
	lockIsHeadless       sync.RWMutex
	lockProjectDir       sync.RWMutex
	lockRespectGitignore sync.RWMutex
}

// ExtensionConfig calls ExtensionConfigFunc.
func (mock *ConfigMock) ExtensionConfig(scope string, name string, target any) error {
	callInfo := struct {
		Scope  string
		Name   string
		Target any
	}{
		Scope:  scope,
		Name:   name,
		Target: target,
	}
	mock.lockExtensionConfig.Lock()
	mock.calls.ExtensionConfig = append(mock.calls.ExtensionConfig, callInfo)
	mock.lockExtensionConfig.Unlock()
	if mock.ExtensionConfigFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ExtensionConfigFunc(scope, name, target)
}

// ExtensionConfigCalls gets all the calls that were made to ExtensionConfig.
// Check the length with:
//
//	len(mockedConfig.ExtensionConfigCalls())
func (mock *ConfigMock) ExtensionConfigCalls() []struct {
	Scope  string
	Name   string
	Target any
} {
	var calls []struct {
		Scope  string
		Name   string
		Target any
	}
	mock.lockExtensionConfig.RLock()
	calls = mock.calls.ExtensionConfig
	mock.lockExtensionConfig.RUnlock()
	return calls
}

// FilePath calls FilePathFunc.
func (mock *ConfigMock) FilePath() string {
	callInfo := struct {
	}{}
	mock.lockFilePath.Lock()
	mock.calls.FilePath = append(mock.calls.FilePath, callInfo)
	mock.lockFilePath.Unlock()
	if mock.FilePathFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.FilePathFunc()
}

// FilePathCalls gets all the calls that were made to FilePath.
// Check the length with:
//
//	len(mockedConfig.FilePathCalls())
func (mock *ConfigMock) FilePathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFilePath.RLock()
	calls = mock.calls.FilePath
	mock.lockFilePath.RUnlock()
	return calls
}

// IsHeadless calls IsHeadlessFunc.
func (mock *ConfigMock) IsHeadless() bool {
	callInfo := struct {
	}{}
	mock.lockIsHeadless.Lock()
	mock.calls.IsHeadless = append(mock.calls.IsHeadless, callInfo)
	mock.lockIsHeadless.Unlock()
	if mock.IsHeadlessFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.IsHeadlessFunc()
}

// IsHeadlessCalls gets all the calls that were made to IsHeadless.
// Check the length with:
//
//	len(mockedConfig.IsHeadlessCalls())
func (mock *ConfigMock) IsHeadlessCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsHeadless.RLock()
	calls = mock.calls.IsHeadless
	mock.lockIsHeadless.RUnlock()
	return calls
}

// ProjectDir calls ProjectDirFunc.
func (mock *ConfigMock) ProjectDir() string {
	callInfo := struct {
	}{}
	mock.lockProjectDir.Lock()
	mock.calls.ProjectDir = append(mock.calls.ProjectDir, callInfo)
	mock.lockProjectDir.Unlock()
	if mock.ProjectDirFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.ProjectDirFunc()
}

// ProjectDirCalls gets all the calls that were made to ProjectDir.
// Check the length with:
//
//	len(mockedConfig.ProjectDirCalls())
func (mock *ConfigMock) ProjectDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjectDir.RLock()
	calls = mock.calls.ProjectDir
	mock.lockProjectDir.RUnlock()
	return calls
}

// RespectGitignore calls RespectGitignoreFunc.
func (mock *ConfigMock) RespectGitignore() bool {
	callInfo := struct {
	}{}
	mock.lockRespectGitignore.Lock()
	mock.calls.RespectGitignore = append(mock.calls.RespectGitignore, callInfo)
	mock.lockRespectGitignore.Unlock()
	if mock.RespectGitignoreFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.RespectGitignoreFunc()
}

// RespectGitignoreCalls gets all the calls that were made to RespectGitignore.
// Check the length with:
//
//	len(mockedConfig.RespectGitignoreCalls())
func (mock *ConfigMock) RespectGitignoreCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRespectGitignore.RLock()
	calls = mock.calls.RespectGitignore
	mock.lockRespectGitignore.RUnlock()
	return calls
}
