// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sdk

import (
	"sync"
)

// Ensure, that ConfigMock does implement Config.
// If this is not the case, regenerate this file with moq.
var _ Config = &ConfigMock{}

// ConfigMock is a mock implementation of Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked Config
//		mockedConfig := &ConfigMock{
//			FilePathFunc: func() string {
//				panic("mock out the FilePath method")
//			},
//			IsHeadlessFunc: func() bool {
//				panic("mock out the IsHeadless method")
//			},
//			ProviderConfigFunc: func(name string) *ProviderConfigEntry {
//				panic("mock out the ProviderConfig method")
//			},
//			ResolveKeyFunc: func(providerName string, envVar string) (string, error) {
//				panic("mock out the ResolveKey method")
//			},
//			ToolConfigFunc: func(name string, target any) error {
//				panic("mock out the ToolConfig method")
//			},
//			UIConfigFunc: func(target any) error {
//				panic("mock out the UIConfig method")
//			},
//		}
//
//		// use mockedConfig in code that requires Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// FilePathFunc mocks the FilePath method.
	FilePathFunc func() string

	// IsHeadlessFunc mocks the IsHeadless method.
	IsHeadlessFunc func() bool

	// ProviderConfigFunc mocks the ProviderConfig method.
	ProviderConfigFunc func(name string) *ProviderConfigEntry

	// ResolveKeyFunc mocks the ResolveKey method.
	ResolveKeyFunc func(providerName string, envVar string) (string, error)

	// ToolConfigFunc mocks the ToolConfig method.
	ToolConfigFunc func(name string, target any) error

	// UIConfigFunc mocks the UIConfig method.
	UIConfigFunc func(target any) error

	// calls tracks calls to the methods.
	calls struct {
		// FilePath holds details about calls to the FilePath method.
		FilePath []struct {
		}
		// IsHeadless holds details about calls to the IsHeadless method.
		IsHeadless []struct {
		}
		// ProviderConfig holds details about calls to the ProviderConfig method.
		ProviderConfig []struct {
			// Name is the name argument value.
			Name string
		}
		// ResolveKey holds details about calls to the ResolveKey method.
		ResolveKey []struct {
			// ProviderName is the providerName argument value.
			ProviderName string
			// EnvVar is the envVar argument value.
			EnvVar string
		}
		// ToolConfig holds details about calls to the ToolConfig method.
		ToolConfig []struct {
			// Name is the name argument value.
			Name string
			// Target is the target argument value.
			Target any
		}
		// UIConfig holds details about calls to the UIConfig method.
		UIConfig []struct {
			// Target is the target argument value.
			Target any
		}
	}
	lockFilePath       sync.RWMutex
	lockIsHeadless     sync.RWMutex
	lockProviderConfig sync.RWMutex
	lockResolveKey     sync.RWMutex
	lockToolConfig     sync.RWMutex
	lockUIConfig       sync.RWMutex
}

// FilePath calls FilePathFunc.
func (mock *ConfigMock) FilePath() string {
	callInfo := struct {
	}{}
	mock.lockFilePath.Lock()
	mock.calls.FilePath = append(mock.calls.FilePath, callInfo)
	mock.lockFilePath.Unlock()
	if mock.FilePathFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.FilePathFunc()
}

// FilePathCalls gets all the calls that were made to FilePath.
// Check the length with:
//
//	len(mockedConfig.FilePathCalls())
func (mock *ConfigMock) FilePathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFilePath.RLock()
	calls = mock.calls.FilePath
	mock.lockFilePath.RUnlock()
	return calls
}

// IsHeadless calls IsHeadlessFunc.
func (mock *ConfigMock) IsHeadless() bool {
	callInfo := struct {
	}{}
	mock.lockIsHeadless.Lock()
	mock.calls.IsHeadless = append(mock.calls.IsHeadless, callInfo)
	mock.lockIsHeadless.Unlock()
	if mock.IsHeadlessFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.IsHeadlessFunc()
}

// IsHeadlessCalls gets all the calls that were made to IsHeadless.
// Check the length with:
//
//	len(mockedConfig.IsHeadlessCalls())
func (mock *ConfigMock) IsHeadlessCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsHeadless.RLock()
	calls = mock.calls.IsHeadless
	mock.lockIsHeadless.RUnlock()
	return calls
}

// ProviderConfig calls ProviderConfigFunc.
func (mock *ConfigMock) ProviderConfig(name string) *ProviderConfigEntry {
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockProviderConfig.Lock()
	mock.calls.ProviderConfig = append(mock.calls.ProviderConfig, callInfo)
	mock.lockProviderConfig.Unlock()
	if mock.ProviderConfigFunc == nil {
		var (
			providerConfigEntryOut *ProviderConfigEntry
		)
		return providerConfigEntryOut
	}
	return mock.ProviderConfigFunc(name)
}

// ProviderConfigCalls gets all the calls that were made to ProviderConfig.
// Check the length with:
//
//	len(mockedConfig.ProviderConfigCalls())
func (mock *ConfigMock) ProviderConfigCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockProviderConfig.RLock()
	calls = mock.calls.ProviderConfig
	mock.lockProviderConfig.RUnlock()
	return calls
}

// ResolveKey calls ResolveKeyFunc.
func (mock *ConfigMock) ResolveKey(providerName string, envVar string) (string, error) {
	callInfo := struct {
		ProviderName string
		EnvVar       string
	}{
		ProviderName: providerName,
		EnvVar:       envVar,
	}
	mock.lockResolveKey.Lock()
	mock.calls.ResolveKey = append(mock.calls.ResolveKey, callInfo)
	mock.lockResolveKey.Unlock()
	if mock.ResolveKeyFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.ResolveKeyFunc(providerName, envVar)
}

// ResolveKeyCalls gets all the calls that were made to ResolveKey.
// Check the length with:
//
//	len(mockedConfig.ResolveKeyCalls())
func (mock *ConfigMock) ResolveKeyCalls() []struct {
	ProviderName string
	EnvVar       string
} {
	var calls []struct {
		ProviderName string
		EnvVar       string
	}
	mock.lockResolveKey.RLock()
	calls = mock.calls.ResolveKey
	mock.lockResolveKey.RUnlock()
	return calls
}

// ToolConfig calls ToolConfigFunc.
func (mock *ConfigMock) ToolConfig(name string, target any) error {
	callInfo := struct {
		Name   string
		Target any
	}{
		Name:   name,
		Target: target,
	}
	mock.lockToolConfig.Lock()
	mock.calls.ToolConfig = append(mock.calls.ToolConfig, callInfo)
	mock.lockToolConfig.Unlock()
	if mock.ToolConfigFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ToolConfigFunc(name, target)
}

// ToolConfigCalls gets all the calls that were made to ToolConfig.
// Check the length with:
//
//	len(mockedConfig.ToolConfigCalls())
func (mock *ConfigMock) ToolConfigCalls() []struct {
	Name   string
	Target any
} {
	var calls []struct {
		Name   string
		Target any
	}
	mock.lockToolConfig.RLock()
	calls = mock.calls.ToolConfig
	mock.lockToolConfig.RUnlock()
	return calls
}

// UIConfig calls UIConfigFunc.
func (mock *ConfigMock) UIConfig(target any) error {
	callInfo := struct {
		Target any
	}{
		Target: target,
	}
	mock.lockUIConfig.Lock()
	mock.calls.UIConfig = append(mock.calls.UIConfig, callInfo)
	mock.lockUIConfig.Unlock()
	if mock.UIConfigFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UIConfigFunc(target)
}

// UIConfigCalls gets all the calls that were made to UIConfig.
// Check the length with:
//
//	len(mockedConfig.UIConfigCalls())
func (mock *ConfigMock) UIConfigCalls() []struct {
	Target any
} {
	var calls []struct {
		Target any
	}
	mock.lockUIConfig.RLock()
	calls = mock.calls.UIConfig
	mock.lockUIConfig.RUnlock()
	return calls
}
