// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sdk

import (
	"context"
	"sync"
)

// Ensure, that GuardianMock does implement Guardian.
// If this is not the case, regenerate this file with moq.
var _ Guardian = &GuardianMock{}

// GuardianMock is a mock implementation of Guardian.
//
//	func TestSomethingThatUsesGuardian(t *testing.T) {
//
//		// make and configure a mocked Guardian
//		mockedGuardian := &GuardianMock{
//			DecideFunc: func(ctx context.Context, req GuardianRequest) (GuardianDecision, error) {
//				panic("mock out the Decide method")
//			},
//			ResolveFunc: func(ctx context.Context, decisionID string, resolution GuardianResolution) error {
//				panic("mock out the Resolve method")
//			},
//			SnapshotFunc: func(ctx context.Context) (GuardianSnapshot, error) {
//				panic("mock out the Snapshot method")
//			},
//		}
//
//		// use mockedGuardian in code that requires Guardian
//		// and then make assertions.
//
//	}
type GuardianMock struct {
	// DecideFunc mocks the Decide method.
	DecideFunc func(ctx context.Context, req GuardianRequest) (GuardianDecision, error)

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, decisionID string, resolution GuardianResolution) error

	// SnapshotFunc mocks the Snapshot method.
	SnapshotFunc func(ctx context.Context) (GuardianSnapshot, error)

	// calls tracks calls to the methods.
	calls struct {
		// Decide holds details about calls to the Decide method.
		Decide []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req GuardianRequest
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DecisionID is the decisionID argument value.
			DecisionID string
			// Resolution is the resolution argument value.
			Resolution GuardianResolution
		}
		// Snapshot holds details about calls to the Snapshot method.
		Snapshot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockDecide   sync.RWMutex
	lockResolve  sync.RWMutex
	lockSnapshot sync.RWMutex
}

// Decide calls DecideFunc.
func (mock *GuardianMock) Decide(ctx context.Context, req GuardianRequest) (GuardianDecision, error) {
	callInfo := struct {
		Ctx context.Context
		Req GuardianRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockDecide.Lock()
	mock.calls.Decide = append(mock.calls.Decide, callInfo)
	mock.lockDecide.Unlock()
	if mock.DecideFunc == nil {
		var (
			guardianDecisionOut GuardianDecision
			errOut              error
		)
		return guardianDecisionOut, errOut
	}
	return mock.DecideFunc(ctx, req)
}

// DecideCalls gets all the calls that were made to Decide.
// Check the length with:
//
//	len(mockedGuardian.DecideCalls())
func (mock *GuardianMock) DecideCalls() []struct {
	Ctx context.Context
	Req GuardianRequest
} {
	var calls []struct {
		Ctx context.Context
		Req GuardianRequest
	}
	mock.lockDecide.RLock()
	calls = mock.calls.Decide
	mock.lockDecide.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *GuardianMock) Resolve(ctx context.Context, decisionID string, resolution GuardianResolution) error {
	callInfo := struct {
		Ctx        context.Context
		DecisionID string
		Resolution GuardianResolution
	}{
		Ctx:        ctx,
		DecisionID: decisionID,
		Resolution: resolution,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	if mock.ResolveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ResolveFunc(ctx, decisionID, resolution)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedGuardian.ResolveCalls())
func (mock *GuardianMock) ResolveCalls() []struct {
	Ctx        context.Context
	DecisionID string
	Resolution GuardianResolution
} {
	var calls []struct {
		Ctx        context.Context
		DecisionID string
		Resolution GuardianResolution
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Snapshot calls SnapshotFunc.
func (mock *GuardianMock) Snapshot(ctx context.Context) (GuardianSnapshot, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSnapshot.Lock()
	mock.calls.Snapshot = append(mock.calls.Snapshot, callInfo)
	mock.lockSnapshot.Unlock()
	if mock.SnapshotFunc == nil {
		var (
			guardianSnapshotOut GuardianSnapshot
			errOut              error
		)
		return guardianSnapshotOut, errOut
	}
	return mock.SnapshotFunc(ctx)
}

// SnapshotCalls gets all the calls that were made to Snapshot.
// Check the length with:
//
//	len(mockedGuardian.SnapshotCalls())
func (mock *GuardianMock) SnapshotCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSnapshot.RLock()
	calls = mock.calls.Snapshot
	mock.lockSnapshot.RUnlock()
	return calls
}
