// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sdk

import (
	"context"
	"sync"
)

// Ensure, that SandboxerMock does implement Sandboxer.
// If this is not the case, regenerate this file with moq.
var _ Sandboxer = &SandboxerMock{}

// SandboxerMock is a mock implementation of Sandboxer.
//
//	func TestSomethingThatUsesSandboxer(t *testing.T) {
//
//		// make and configure a mocked Sandboxer
//		mockedSandboxer := &SandboxerMock{
//			RequestExpansionFunc: func(ctx context.Context, req SandboxExpansionRequest) (SandboxExpansion, error) {
//				panic("mock out the RequestExpansion method")
//			},
//			ResolveExpansionFunc: func(ctx context.Context, expansionID string, resolution SandboxExpansionResolution) error {
//				panic("mock out the ResolveExpansion method")
//			},
//			StatusFunc: func(ctx context.Context) (SandboxStatus, error) {
//				panic("mock out the Status method")
//			},
//			WrapCommandFunc: func(ctx context.Context, req SandboxCommandRequest) (SandboxCommand, error) {
//				panic("mock out the WrapCommand method")
//			},
//		}
//
//		// use mockedSandboxer in code that requires Sandboxer
//		// and then make assertions.
//
//	}
type SandboxerMock struct {
	// RequestExpansionFunc mocks the RequestExpansion method.
	RequestExpansionFunc func(ctx context.Context, req SandboxExpansionRequest) (SandboxExpansion, error)

	// ResolveExpansionFunc mocks the ResolveExpansion method.
	ResolveExpansionFunc func(ctx context.Context, expansionID string, resolution SandboxExpansionResolution) error

	// StatusFunc mocks the Status method.
	StatusFunc func(ctx context.Context) (SandboxStatus, error)

	// WrapCommandFunc mocks the WrapCommand method.
	WrapCommandFunc func(ctx context.Context, req SandboxCommandRequest) (SandboxCommand, error)

	// calls tracks calls to the methods.
	calls struct {
		// RequestExpansion holds details about calls to the RequestExpansion method.
		RequestExpansion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req SandboxExpansionRequest
		}
		// ResolveExpansion holds details about calls to the ResolveExpansion method.
		ResolveExpansion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExpansionID is the expansionID argument value.
			ExpansionID string
			// Resolution is the resolution argument value.
			Resolution SandboxExpansionResolution
		}
		// Status holds details about calls to the Status method.
		Status []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// WrapCommand holds details about calls to the WrapCommand method.
		WrapCommand []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req SandboxCommandRequest
		}
	}
	lockRequestExpansion sync.RWMutex
	lockResolveExpansion sync.RWMutex
	lockStatus           sync.RWMutex
	lockWrapCommand      sync.RWMutex
}

// RequestExpansion calls RequestExpansionFunc.
func (mock *SandboxerMock) RequestExpansion(ctx context.Context, req SandboxExpansionRequest) (SandboxExpansion, error) {
	if mock.RequestExpansionFunc == nil {
		panic("SandboxerMock.RequestExpansionFunc: method is nil but Sandboxer.RequestExpansion was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req SandboxExpansionRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRequestExpansion.Lock()
	mock.calls.RequestExpansion = append(mock.calls.RequestExpansion, callInfo)
	mock.lockRequestExpansion.Unlock()
	return mock.RequestExpansionFunc(ctx, req)
}

// RequestExpansionCalls gets all the calls that were made to RequestExpansion.
// Check the length with:
//
//	len(mockedSandboxer.RequestExpansionCalls())
func (mock *SandboxerMock) RequestExpansionCalls() []struct {
	Ctx context.Context
	Req SandboxExpansionRequest
} {
	var calls []struct {
		Ctx context.Context
		Req SandboxExpansionRequest
	}
	mock.lockRequestExpansion.RLock()
	calls = mock.calls.RequestExpansion
	mock.lockRequestExpansion.RUnlock()
	return calls
}

// ResolveExpansion calls ResolveExpansionFunc.
func (mock *SandboxerMock) ResolveExpansion(ctx context.Context, expansionID string, resolution SandboxExpansionResolution) error {
	if mock.ResolveExpansionFunc == nil {
		panic("SandboxerMock.ResolveExpansionFunc: method is nil but Sandboxer.ResolveExpansion was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ExpansionID string
		Resolution  SandboxExpansionResolution
	}{
		Ctx:         ctx,
		ExpansionID: expansionID,
		Resolution:  resolution,
	}
	mock.lockResolveExpansion.Lock()
	mock.calls.ResolveExpansion = append(mock.calls.ResolveExpansion, callInfo)
	mock.lockResolveExpansion.Unlock()
	return mock.ResolveExpansionFunc(ctx, expansionID, resolution)
}

// ResolveExpansionCalls gets all the calls that were made to ResolveExpansion.
// Check the length with:
//
//	len(mockedSandboxer.ResolveExpansionCalls())
func (mock *SandboxerMock) ResolveExpansionCalls() []struct {
	Ctx         context.Context
	ExpansionID string
	Resolution  SandboxExpansionResolution
} {
	var calls []struct {
		Ctx         context.Context
		ExpansionID string
		Resolution  SandboxExpansionResolution
	}
	mock.lockResolveExpansion.RLock()
	calls = mock.calls.ResolveExpansion
	mock.lockResolveExpansion.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *SandboxerMock) Status(ctx context.Context) (SandboxStatus, error) {
	if mock.StatusFunc == nil {
		panic("SandboxerMock.StatusFunc: method is nil but Sandboxer.Status was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	mock.lockStatus.Unlock()
	return mock.StatusFunc(ctx)
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//
//	len(mockedSandboxer.StatusCalls())
func (mock *SandboxerMock) StatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStatus.RLock()
	calls = mock.calls.Status
	mock.lockStatus.RUnlock()
	return calls
}

// WrapCommand calls WrapCommandFunc.
func (mock *SandboxerMock) WrapCommand(ctx context.Context, req SandboxCommandRequest) (SandboxCommand, error) {
	if mock.WrapCommandFunc == nil {
		panic("SandboxerMock.WrapCommandFunc: method is nil but Sandboxer.WrapCommand was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req SandboxCommandRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockWrapCommand.Lock()
	mock.calls.WrapCommand = append(mock.calls.WrapCommand, callInfo)
	mock.lockWrapCommand.Unlock()
	return mock.WrapCommandFunc(ctx, req)
}

// WrapCommandCalls gets all the calls that were made to WrapCommand.
// Check the length with:
//
//	len(mockedSandboxer.WrapCommandCalls())
func (mock *SandboxerMock) WrapCommandCalls() []struct {
	Ctx context.Context
	Req SandboxCommandRequest
} {
	var calls []struct {
		Ctx context.Context
		Req SandboxCommandRequest
	}
	mock.lockWrapCommand.RLock()
	calls = mock.calls.WrapCommand
	mock.lockWrapCommand.RUnlock()
	return calls
}
