// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sdk

import (
	"sync"
)

// Ensure, that SandboxerMock does implement Sandboxer.
// If this is not the case, regenerate this file with moq.
var _ Sandboxer = &SandboxerMock{}

// SandboxerMock is a mock implementation of Sandboxer.
//
//	func TestSomethingThatUsesSandboxer(t *testing.T) {
//
//		// make and configure a mocked Sandboxer
//		mockedSandboxer := &SandboxerMock{
//			AllowReadFunc: func(path string) bool {
//				panic("mock out the AllowRead method")
//			},
//			AllowWriteFunc: func(path string) bool {
//				panic("mock out the AllowWrite method")
//			},
//			ModeFunc: func() string {
//				panic("mock out the Mode method")
//			},
//			SetModeFunc: func(mode string)  {
//				panic("mock out the SetMode method")
//			},
//			WrapCommandFunc: func(cmd string, dir string) (string, error) {
//				panic("mock out the WrapCommand method")
//			},
//		}
//
//		// use mockedSandboxer in code that requires Sandboxer
//		// and then make assertions.
//
//	}
type SandboxerMock struct {
	// AllowReadFunc mocks the AllowRead method.
	AllowReadFunc func(path string) bool

	// AllowWriteFunc mocks the AllowWrite method.
	AllowWriteFunc func(path string) bool

	// ModeFunc mocks the Mode method.
	ModeFunc func() string

	// SetModeFunc mocks the SetMode method.
	SetModeFunc func(mode string)

	// WrapCommandFunc mocks the WrapCommand method.
	WrapCommandFunc func(cmd, dir string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// AllowRead holds details about calls to the AllowRead method.
		AllowRead []struct {
			// Path is the path argument value.
			Path string
		}
		// AllowWrite holds details about calls to the AllowWrite method.
		AllowWrite []struct {
			// Path is the path argument value.
			Path string
		}
		// Mode holds details about calls to the Mode method.
		Mode []struct{}
		// SetMode holds details about calls to the SetMode method.
		SetMode []struct {
			// Mode is the mode argument value.
			Mode string
		}
		// WrapCommand holds details about calls to the WrapCommand method.
		WrapCommand []struct {
			// Cmd is the cmd argument value.
			Cmd string
			// Dir is the dir argument value.
			Dir string
		}
	}
	lockAllowRead   sync.RWMutex
	lockAllowWrite  sync.RWMutex
	lockMode        sync.RWMutex
	lockSetMode     sync.RWMutex
	lockWrapCommand sync.RWMutex
}

// AllowRead calls AllowReadFunc.
func (mock *SandboxerMock) AllowRead(path string) bool {
	if mock.AllowReadFunc == nil {
		panic("SandboxerMock.AllowReadFunc: method is nil but Sandboxer.AllowRead was just called")
	}

	callInfo := struct {
		Path string
	}{
		Path: path,
	}

	mock.lockAllowRead.Lock()
	mock.calls.AllowRead = append(mock.calls.AllowRead, callInfo)
	mock.lockAllowRead.Unlock()

	return mock.AllowReadFunc(path)
}

// AllowReadCalls gets all the calls that were made to AllowRead.
// Check the length with:
//
//	len(mockedSandboxer.AllowReadCalls())
func (mock *SandboxerMock) AllowReadCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}

	mock.lockAllowRead.RLock()
	calls = mock.calls.AllowRead
	mock.lockAllowRead.RUnlock()

	return calls
}

// AllowWrite calls AllowWriteFunc.
func (mock *SandboxerMock) AllowWrite(path string) bool {
	if mock.AllowWriteFunc == nil {
		panic("SandboxerMock.AllowWriteFunc: method is nil but Sandboxer.AllowWrite was just called")
	}

	callInfo := struct {
		Path string
	}{
		Path: path,
	}

	mock.lockAllowWrite.Lock()
	mock.calls.AllowWrite = append(mock.calls.AllowWrite, callInfo)
	mock.lockAllowWrite.Unlock()

	return mock.AllowWriteFunc(path)
}

// AllowWriteCalls gets all the calls that were made to AllowWrite.
// Check the length with:
//
//	len(mockedSandboxer.AllowWriteCalls())
func (mock *SandboxerMock) AllowWriteCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}

	mock.lockAllowWrite.RLock()
	calls = mock.calls.AllowWrite
	mock.lockAllowWrite.RUnlock()

	return calls
}

// Mode calls ModeFunc.
func (mock *SandboxerMock) Mode() string {
	if mock.ModeFunc == nil {
		panic("SandboxerMock.ModeFunc: method is nil but Sandboxer.Mode was just called")
	}

	callInfo := struct{}{}

	mock.lockMode.Lock()
	mock.calls.Mode = append(mock.calls.Mode, callInfo)
	mock.lockMode.Unlock()

	return mock.ModeFunc()
}

// ModeCalls gets all the calls that were made to Mode.
// Check the length with:
//
//	len(mockedSandboxer.ModeCalls())
func (mock *SandboxerMock) ModeCalls() []struct{} {
	var calls []struct{}

	mock.lockMode.RLock()
	calls = mock.calls.Mode
	mock.lockMode.RUnlock()

	return calls
}

// SetMode calls SetModeFunc.
func (mock *SandboxerMock) SetMode(mode string) {
	if mock.SetModeFunc == nil {
		panic("SandboxerMock.SetModeFunc: method is nil but Sandboxer.SetMode was just called")
	}

	callInfo := struct {
		Mode string
	}{
		Mode: mode,
	}

	mock.lockSetMode.Lock()
	mock.calls.SetMode = append(mock.calls.SetMode, callInfo)
	mock.lockSetMode.Unlock()
	mock.SetModeFunc(mode)
}

// SetModeCalls gets all the calls that were made to SetMode.
// Check the length with:
//
//	len(mockedSandboxer.SetModeCalls())
func (mock *SandboxerMock) SetModeCalls() []struct {
	Mode string
} {
	var calls []struct {
		Mode string
	}

	mock.lockSetMode.RLock()
	calls = mock.calls.SetMode
	mock.lockSetMode.RUnlock()

	return calls
}

// WrapCommand calls WrapCommandFunc.
func (mock *SandboxerMock) WrapCommand(cmd, dir string) (string, error) {
	if mock.WrapCommandFunc == nil {
		panic("SandboxerMock.WrapCommandFunc: method is nil but Sandboxer.WrapCommand was just called")
	}

	callInfo := struct {
		Cmd string
		Dir string
	}{
		Cmd: cmd,
		Dir: dir,
	}

	mock.lockWrapCommand.Lock()
	mock.calls.WrapCommand = append(mock.calls.WrapCommand, callInfo)
	mock.lockWrapCommand.Unlock()

	return mock.WrapCommandFunc(cmd, dir)
}

// WrapCommandCalls gets all the calls that were made to WrapCommand.
// Check the length with:
//
//	len(mockedSandboxer.WrapCommandCalls())
func (mock *SandboxerMock) WrapCommandCalls() []struct {
	Cmd string
	Dir string
} {
	var calls []struct {
		Cmd string
		Dir string
	}

	mock.lockWrapCommand.RLock()
	calls = mock.calls.WrapCommand
	mock.lockWrapCommand.RUnlock()

	return calls
}
